package com.taskmanagement.common.exception.ErrorCode;

import jakarta.persistence.AssociationOverride;

public enum ErrorCode {
    EMAIL_ALREADY_REGISTERED,
    USER_NOT_FOUND,
    USER_ALREADY_ACTIVE,
    USER_NOT_ACTIVE,
    USER_IS_SUSPENDED,
    USER_IS_NOT_DELETED,
    USER_IS_NOT_AN_ADMIN,
    INVALID_STATUES_TRANSITION,
    CANNOT_DELETE_LAST_ADMIN,
    UNAUTHORIZED_OPERATION,
    SELF_OPERATION_NOT_ALLOWED,
    INVALID_ROLE_TRANSITION,
    INVALID_PASSWORD,
    LAST_ADMIN_ROLE_CHANGE_NOT_ALLOWED,
    LAST_ADMIN_DEACTIVATION_NOT_ALLOWED,
    ACCESS_DENIED,
    CANNOT_DELETE_OWN_ACCOUNT
    ;


}
