package com.taskmanagement.common.exception.ErrorCode;


public enum ErrorCode {


    INVALID_REQUEST,
    EMAIL_ALREADY_REGISTERED,
    USER_NOT_FOUND,
    USER_ALREADY_ACTIVE,
    USER_NOT_ACTIVE,
    USER_IS_SUSPENDED,
    USER_IS_NOT_DELETED,
    USER_IS_NOT_AN_ADMIN,
    INVALID_STATUES_TRANSITION,
    CANNOT_DELETE_LAST_ADMIN,
    UNAUTHORIZED_OPERATION,
    SELF_OPERATION_NOT_ALLOWED,
    INVALID_ROLE_TRANSITION,
    INVALID_PASSWORD,
    LAST_ADMIN_ROLE_CHANGE_NOT_ALLOWED,
    LAST_ADMIN_DEACTIVATION_NOT_ALLOWED,
    ACCESS_DENIED,
    CANNOT_DELETE_OWN_ACCOUNT,
    TEAM_NOT_FOUND,
    TEAM_NAME_ALREADY_EXISTS,
    USER_ALREADY_IN_TEAM ,
    TEAM_MEMBER_NOT_FOUND,
    TEAM_ALREADY_ARCHIVED,
    TEAM_ALREADY_DELETED,
    TEAM_ALREADY_ACTIVE,
    USER_NOT_FOUND_IN_TEAM,
    INVALID_PROJECT_STATUS,
    PROJECT_NAME_ALREADY_EXISTS,
    PROJECT_NOT_FOUND,
    INVALID_PROJECT_DATE,
    CANNOT_ARCHIVE_ACTIVE_PROJECT,
    CANNOT_MODIFY_ARCHIVED_PROJECT,
    TASK_NOT_FOUND,
    INVALID_TASK_STATUS,
    INVALID_TASK_PRIORITY,
    CANNOT_MODIFY_COMPLETED_TASK,
    CANNOT_ARCHIVE_PROJECT_WITH_ACTIVE_TASKS,
    TASK_TITLE_ALREADY_EXISTS,
    COMMENT_NOT_FOUND,
    ATTACHMENT_NOT_FOUND


    ;

}
